# Uses latest blueocean plugin version and jenkins LTS
FROM jenkinsci/blueocean:latest

LABEL maintainer="gabrielvilloldo@gmail.com"

USER root

# Adds docker so we can use it inside of container
RUN apk -U add docker docker-compose
